//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BungieBoggleTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BungieBoggleTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///3
        ///yox
        ///rba
        ///ved
        ///.
        /// </summary>
        public static string boggleGrid1 {
            get {
                return ResourceManager.GetString("boggleGrid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Users\Michael\Source\Repos\BungieBoggleTool\BungieBoggleTool\BungieBoggleTool\Resources\boggleGrid1.txt.
        /// </summary>
        public static string BOGGLEGRID1_FILEPATH {
            get {
                return ResourceManager.GetString("BOGGLEGRID1_FILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Users\Michael\Source\Repos\BungieBoggleTool\BungieBoggleTool\BungieBoggleTool\Resources\boggleGrid1Solution.txt.
        /// </summary>
        public static string BOGGLEGRID1_SOLUTION_FILEPATH {
            get {
                return ResourceManager.GetString("BOGGLEGRID1_SOLUTION_FILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bred
        ///yore
        ///byre
        ///abed
        ///oread
        ///bore
        ///orby
        ///robed
        ///broad
        ///byroad
        ///robe
        ///bored
        ///derby
        ///bade
        ///aero
        ///read
        ///orbed
        ///verb
        ///aery
        ///bead
        ///bread
        ///very
        ///road.
        /// </summary>
        public static string boggleGrid1Solution {
            get {
                return ResourceManager.GetString("boggleGrid1Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///2
        ///CO
        ///AT.
        /// </summary>
        public static string boggleGrid2 {
            get {
                return ResourceManager.GetString("boggleGrid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Users\Michael\Source\Repos\BungieBoggleTool\BungieBoggleTool\BungieBoggleTool\Resources\boggleGrid2.txt.
        /// </summary>
        public static string BOGGLEGRID2_FILEPATH {
            get {
                return ResourceManager.GetString("BOGGLEGRID2_FILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coat
        ///taco.
        /// </summary>
        public static string boggleGrid2Solution {
            get {
                return ResourceManager.GetString("boggleGrid2Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BungieBoggleTool {
            get {
                object obj = ResourceManager.GetObject("BungieBoggleTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///6
        ///plrntp
        ///lnprce
        ///rpxeck
        ///nreimq
        ///tccmmw
        ///pekqwb
        ///.
        /// </summary>
        public static string gBoggleGrid0 {
            get {
                return ResourceManager.GetString("gBoggleGrid0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premier
        ///precept
        ///percept
        ///premix
        ///expect
        ///expert
        ///premie
        ///recept
        ///mixer
        ///exert
        ///mimer
        ///cerci
        ///creep
        ///cimex
        ///emmer
        ///remix
        ///prex
        ///rep
        ///rec
        ///ick
        ///ice
        ///mix
        ///rex
        ///rei
        ///peck
        ///reck
        ///mim
        ///cee
        ///exec
        ///tree
        ///pert
        ///rem
        ///repp
        ///per
        ///mick
        ///cep
        ///peer
        ///mice
        ///pee
        ///kep
        ///peep
        ///kept
        ///err
        ///emic
        ///pet
        ///pree
        ///mime
        ///ern
        ///ree.
        /// </summary>
        public static string gBoggleGrid0Solution {
            get {
                return ResourceManager.GetString("gBoggleGrid0Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///6
        ///fbhdjf
        ///bdfrtv
        ///hfnvta
        ///drvzcg
        ///jttccm
        ///fvagms
        ///.
        /// </summary>
        public static string gBoggleGrid1 {
            get {
                return ResourceManager.GetString("gBoggleGrid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cat
        ///tat
        ///vat
        ///act
        ///vac
        ///gat
        ///tact
        ///tav
        ///tag.
        /// </summary>
        public static string gBoggleGrid1Solution {
            get {
                return ResourceManager.GetString("gBoggleGrid1Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///6
        ///cxavzt
        ///xvtrpn
        ///atvnfh
        ///vrnjfb
        ///zpffww
        ///tnhbwg
        ///.
        /// </summary>
        public static string gBoggleGrid2 {
            get {
                return ResourceManager.GetString("gBoggleGrid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attar
        ///att
        ///tarn
        ///art
        ///prat
        ///tar
        ///tax
        ///rat
        ///frat
        ///vat
        ///tav
        ///rax
        ///ava
        ///arf
        ///var
        ///vav
        ///tarp.
        /// </summary>
        public static string gBoggleGrid2Solution {
            get {
                return ResourceManager.GetString("gBoggleGrid2Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///10
        ///ezkeicgaez
        ///gecazxvtrp
        ///kcexzrjldf
        ///eaxtplhd#m
        ///izzpffwmmc
        ///cxrlf#kezt
        ///gvjhwkixlj
        ///atldmexph#
        ///erd#mzlhug
        ///zpfmctj#gx
        ///.
        /// </summary>
        public static string gBoggleGrid3 {
            get {
                return ResourceManager.GetString("gBoggleGrid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace
        ///are
        ///art
        ///ate
        ///axe
        ///cake
        ///drag
        ///drat
        ///dwelt
        ///ear
        ///earl
        ///eat
        ///eke
        ///era
        ///frat
        ///fret
        ///gate
        ///gee
        ///geek
        ///hmm
        ///hug
        ///huh
        ///keg
        ///kelp
        ///kike
        ///kip
        ///lewd
        ///melt
        ///mew
        ///pea
        ///pear
        ///pearl
        ///peat
        ///per
        ///pert
        ///pet
        ///pie
        ///pike
        ///pix
        ///pixel
        ///prat
        ///prate
        ///pug
        ///quip
        ///rag
        ///rat
        ///rate
        ///rep
        ///tag
        ///tar
        ///tarp
        ///tea
        ///teak
        ///tear
        ///tee
        ///ugh
        ///vat
        ///welt.
        /// </summary>
        public static string gBoggleGrid3Solution {
            get {
                return ResourceManager.GetString("gBoggleGrid3Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///aal
        ///aalii
        ///aaliis
        ///aals
        ///aardvark
        ///aardwolf
        ///aargh
        ///aarrgh
        ///aarrghh
        ///aas
        ///aasvogel
        ///aba
        ///abaca
        ///abacas
        ///abaci
        ///aback
        ///abacus
        ///abacuses
        ///abaft
        ///abaka
        ///abakas
        ///abalone
        ///abalones
        ///abamp
        ///abampere
        ///abamps
        ///abandon
        ///abandons
        ///abapical
        ///abas
        ///abase
        ///abased
        ///abasedly
        ///abaser
        ///abasers
        ///abases
        ///abash
        ///abashed
        ///abashes
        ///abashing
        ///abasia
        ///abasias
        ///abasing
        ///abatable
        ///abate
        ///abated
        ///abater
        ///abaters
        ///abates
        ///abating
        ///abatis
        ///abatises
        ///abator
        ///abators
        ///abattis
        ///abattoir
        ///abaxial
        ///abaxile
        ///ab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ospd {
            get {
                return ResourceManager.GetString("ospd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Users\Michael\Source\Repos\BungieBoggleTool\BungieBoggleTool\BungieBoggleTool\Resources\ospd.txt.
        /// </summary>
        public static string OSPD_FILEPATH {
            get {
                return ResourceManager.GetString("OSPD_FILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///aal
        ///aalii
        ///aaliis
        ///aals
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aarrgh
        ///aarrghh
        ///aarti
        ///aartis
        ///aas
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///abac
        ///abaca
        ///abacas
        ///abaci
        ///aback
        ///abacs
        ///abacterial
        ///abactinal
        ///abactinally
        ///abactor
        ///abactors
        ///abacus
        ///abacuses
        ///abaft
        ///abaka
        ///abakas
        ///abalone
        ///abalones
        ///abamp
        ///abampere
        ///abamperes
        ///abamps
        ///aband
        ///abanded
        ///abanding
        ///abandon
        ///abandoned
        ///abandonedly
        ///abandonee
        ///abandonees
        ///abandoner
        ///abandoners
        ///abandoning
        ///abandonment
        ///abandonments
        ///aba [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sowpods {
            get {
                return ResourceManager.GetString("sowpods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Users\Michael\Source\Repos\BungieBoggleTool\BungieBoggleTool\BungieBoggleTool\Resources\sowpods.txt.
        /// </summary>
        public static string SOWPODS_FILEPATH {
            get {
                return ResourceManager.GetString("SOWPODS_FILEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AB
        ///AD
        ///AE
        ///AG
        ///AH
        ///AI
        ///AL
        ///AM
        ///AN
        ///AR
        ///AS
        ///AT
        ///AW
        ///AX
        ///AY
        ///BA
        ///BE
        ///BI
        ///BO
        ///BY
        ///DE
        ///DO
        ///ED
        ///EF
        ///EH
        ///EL
        ///EM
        ///EN
        ///ER
        ///ES
        ///ET
        ///EX
        ///FA
        ///FE
        ///GO
        ///HA
        ///HE
        ///HI
        ///HM
        ///HO
        ///ID
        ///IF
        ///IN
        ///IS
        ///IT
        ///JO
        ///KA
        ///KI
        ///LA
        ///LI
        ///LO
        ///MA
        ///ME
        ///MI
        ///MM
        ///MO
        ///MU
        ///MY
        ///NA
        ///NE
        ///NO
        ///NU
        ///OD
        ///OE
        ///OF
        ///OH
        ///OI
        ///OM
        ///ON
        ///OP
        ///OR
        ///OS
        ///OW
        ///OX
        ///OY
        ///PA
        ///PE
        ///PI
        ///QI
        ///RE
        ///SH
        ///SI
        ///SO
        ///TA
        ///TI
        ///TO
        ///UH
        ///UM
        ///UN
        ///UP
        ///US
        ///UT
        ///WE
        ///WO
        ///XI
        ///XU
        ///YA
        ///YE
        ///YO
        ///ZA
        ///AAH
        ///AAL
        ///AAS
        ///ABA
        ///ABO
        ///ABS
        ///ABY
        ///ACE
        ///ACT
        ///ADD
        ///ADO
        ///ADS
        ///ADZ
        ///AFF
        ///AFT
        ///AGA
        ///AGE
        ///AGO
        ///AGS
        ///AHA
        ///AHI
        ///AHS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TWL_2006_LENGTH {
            get {
                return ResourceManager.GetString("TWL_2006_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Users\Michael\Source\Repos\BungieBoggleTool\BungieBoggleTool\BungieBoggleTool\Resources\TWL_2006_LENGTH.txt.
        /// </summary>
        public static string TWL_FILEPATH {
            get {
                return ResourceManager.GetString("TWL_FILEPATH", resourceCulture);
            }
        }
    }
}
